version: "22"

services:
  app:
    build: 
      context: .
    volumes:
      - .:/frontend
    ports:
      - 3000:3000
    image: app:react
    container_name: react_container
    command: npm start

